name: learn-github-actions
on:
  push:
    paths: '**.json'
jobs:
  json-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: json-lint
        uses: ocular-d/json-linter@0.0.2
        
